# Generated by Django 5.0.3 on 2024-03-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('addresse', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('frais_gestion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copal_manager.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=20)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_bien', models.CharField(max_length=50)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copal_manager.proprietaire')),
            ],
        ),
    ]
