# Generated by Django 5.0.3 on 2024-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='civilite',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame')], default='M', max_length=4),
        ),
    ]
