# Generated by Django 5.0.3 on 2024-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0002_proprietaire_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='numero_contrat',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
