# Generated by Django 5.0.3 on 2024-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0003_contrat_numero_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(blank=True),
        ),
    ]
