# Generated by Django 5.0.3 on 2024-04-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copal_manager', '0005_alter_contrat_date_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietaire',
            old_name='addresse',
            new_name='adresse',
        ),
    ]
